### ISSUE TITLE
4.4.0-RC4 Release Checklist 

### ISSUE THREAD

**Issue by CoHealer** [microsoft/botframework-sdk#5377]
## Package Location
https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily
https://botbuilder.myget.org/gallery/botbuilder-v4-js-daily

## Change Notes
In this release, the team focused on improving and simplifying message and activities handling. The [Bot Framework Activity Schema](https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-activity/botframework-activity.md#conversation-update-activity) is the underlying schema used to define the interaction model for bots. 

Review all changes that went into 4.4 in the detailed change logs:
[[Change Log for .NET](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A4.4+)]   [[Change Log for Node.js](https://github.com/Microsoft/botbuilder-js/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A4.4+)] 

## GitHub Updates
**Create New Branch** @cleemullins
- [X] C#   [4.4](https://github.com/Microsoft/botbuilder-dotnet/tree/4.4)
- [x] JS [4.4](https://github.com/Microsoft/botbuilder-js/tree/4.4)

**Setup Branch Protection on New Branch** @cleemullins
- [X] C#
- [x] JS

**Bump Version on Master** @cleemullins
- [ ] C#
- [ ] JS

**Update Readme.md in master to reflect new branch** @cleemullins
- [X] C#
- [x] JS

**Create DRAFT Release** @cleemullins
- [X] C# [4.4](https://github.com/Microsoft/botbuilder-dotnet/releases/tag/untagged-f1f2d9e1924fc4e02d01)
- [x] JS [4.4](https://github.com/Microsoft/botbuilder-js/releases/edit/untagged-ef83f22873d4bb85ab38)

**Write release notes and change log** @CoHealer 
- [x] C#
- [x] JS

**Update road-map** @yochay 
- [ ] C#
- [ ] JS
- [ ] Java
- [ ] Python

**Apply Release Notes to DRAFT Release** @CoHealer 
- [x] C#
- [x] JS

**Publish GitHub Release** @cleemullins 
- [x] C#
- [x] JS

## Required Signoff

**Teams**  @CoHealer, Sid Uppal
- [x] C# (Ramjot Singh)
- [x] JS (Robin Liao)

**Cortana** @CoHealer, John Bucy
- [x] C# (Bernie Wieser)
- [x] JS (Bernie Wieser)

**Virtual Assistant** @CoHealer, Darren Jefford
- [x] C# (Lauren Mills)
- [x] JS (Implicit, via email)

**Emulator @CoHealer, Chris Whitten
- [ ] C# (Chris Whitten) 
- [ ] JS Chris Whitten)

## Testing Status @jwiley84, @stevkan 
**Console Adapter**
- [x] C#
- [x] JS

**Simple Dialog Flow**
- [x] C#
- [x] JS

**Simple State Management**
- [x] C#
- [x] JS

**Welcome Messages**
- [x] C#
- [x] JS

**Prompts and Prompt Validations**
- [x] C#
- [x] JS

**Standard Cards**
- [x] C#
- [x] JS

**Adaptive Cards**
- [x] C#
- [x] JS

**Card Actions**
- [x] C#
- [x] JS

**Regex Checking**
- [x] C#
- [x] JS

**QnA Maker**
- [x] C#
- [x] JS

**LUIS**
- [x] C#
- [x] JS

**Dispatch**
- [x] C#
- [x] JS

**Attachments**
- [x] C#
- [x] JS

**Proactive Messages**
- [x] C#
- [x] JS

**Middlware**
- [x] C#
- [x] JS

**Translations**
- [x] C#
- [x] JS

**Authentication**
- [x] C#
- [x] JS

**Waterfalls and Dialog Sets**
- [x] C#
- [x] JS

**State Storage**
- [x] C#

**Transcript Logging**
- [x] JS

**Facebook-specific Events**
- [x] C#
- [x] JS

**Cortana Skills (not tested on Cortana channel)**
- [x] C#
- [x] JS

**Application Insights**
- [x] C#
- [x] JS

**Teams**
- [x] C#
- [x] JS

**Enterprise Bot Template**
- [x] C#

**Comment by cleemullins** [comment]
Release is complete. Packages are published.

**Comment by sheelusoniya98774** [comment]
what was the release date
[free movie sites legal
](https://freemoviesite.me/)
[best trail camera for the money uk
](https://wanderviews.net/best-trail-camera/)
[best dash cam low light
](https://wanderviews.net/best-front-and-rear-dash-cams/)
