### ISSUE TITLE
Bot Framework Release Checklist Template

### ISSUE THREAD

**Issue by CoHealer** [microsoft/botframework-sdk#5453]
## Package Location
https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily
https://botbuilder.myget.org/gallery/botbuilder-v4-js-daily

## Change Notes
In this release, the team focused on improving and simplifying message and activities handling. The [Bot Framework Activity Schema](https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-activity/botframework-activity.md#conversation-update-activity) is the underlying schema used to define the interaction model for bots. 

Review all changes that went into 4.x in the detailed change logs:
[[Change Log for .NET](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A4.x+)]   [[Change Log for Node.js](https://github.com/Microsoft/botbuilder-js/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A4x+)] 

## GitHub Updates
**Create New Branch** @cleemullins
- [ ] C# (https://github.com/Microsoft/botbuilder-dotnet/tree/4.x)
- [ ] JS (https://github.com/Microsoft/botbuilder-js/tree/4.x)
- [ ] Python (https://github.com/Microsoft/botbuilder-python/tree/4.x)

**Setup Branch Protection on New Branch** @cleemullins
- [ ] C#
- [ ] JS
- [ ] Python

**Bump Version on Master** @cleemullins
- [ ] C#
- [ ] JS
- [ ] Python

**Update Readme.md in master to reflect new branch** @cleemullins
- [ ] C#
- [ ] JS
- [ ] Python

**Branch Samples** @cleemullins
- [ ] C#
- [ ] JS
- [ ] Python

**Create DRAFT Release** @cleemullins
- [ ] C# (https://github.com/Microsoft/botbuilder-dotnet/releases/tag/untagged-guid)
- [ ] JS (https://github.com/Microsoft/botbuilder-js/releases/edit/untagged-guid)
- [ ] Python (https://github.com/Microsoft/botbuilder-python/releases/edit/untagged-guid)

**Write release notes and change log** @CoHealer 
- [ ] C#
- [ ] JS
- [ ] Python

**Update road-map** @yochay 
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**Apply Release Notes to DRAFT Release** @CoHealer 
- [ ] C#
- [ ] JS
- [ ] Python

**Publish GitHub Release** @cleemullins 
- [ ] C#
- [ ] JS
- [ ] Python

## Required Signoff

**Teams**  @CoHealer, Sid Uppal
- [ ] C# (Ramjot Singh)
- [ ] JS (Robin Liao)
- [ ] Python (TBD)

**Cortana** @CoHealer, John Bucy
- [ ] C# (TBD)
- [ ] JS (TBD)
- [ ] Python (TBD)

**Virtual Assistant** @CoHealer, Darren Jefford
- [ ] C# (Lauren Mills)
- [ ] JS (Implicit, via email)
- [ ] Python (TBD)

**Emulator @CoHealer, Chris Whitten
- [ ] C# (Chris Whitten) 
- [ ] JS Chris Whitten)
- [ ] Python (TBD)

## Testing Status @jwiley84, @stevkan 
**Console Adapter**
- [ ] C#
- [ ] JS
- [ ] Python

**Simple Dialog Flow**
- [ ] C#
- [ ] JS
- [ ] Python

**Simple State Management**
- [ ] C#
- [ ] JS
- [ ] Python

**Welcome Messages**
- [ ] C#
- [ ] JS
- [ ] Python

**Prompts and Prompt Validations**
- [ ] C#
- [ ] JS
- [ ] Python

**Standard Cards**
- [ ] C#
- [ ] JS
- [ ] Python

**Adaptive Cards**
- [ ] C#
- [ ] JS
- [ ] Python

**Card Actions**
- [ ] C#
- [ ] JS
- [ ] Python

**Regex Checking**
- [ ] C#
- [ ] JS
- [ ] Python

**QnA Maker**
- [ ] C#
- [ ] JS
- [ ] Python

**LUIS**
- [ ] C#
- [ ] JS
- [ ] Python

**Dispatch**
- [ ] C#
- [ ] JS
- [ ] Python

**Attachments**
- [ ] C#
- [ ] JS
- [ ] Python

**Proactive Messages**
- [ ] C#
- [ ] JS
- [ ] Python

**Middlware**
- [ ] C#
- [ ] JS
- [ ] Python

**Translations**
- [ ] C#
- [ ] JS
- [ ] Python

**Authentication**
- [ ] C#
- [ ] JS
- [ ] Python

**Waterfalls and Dialog Sets**
- [ ] C#

**State Storage**
- [ ] C#
- [ ] JS
- [ ] Python

**Transcript Logging**
- [ ] C#
- [ ] JS
- [ ] Python

**Facebook-specific Events**
- [ ] C#
- [ ] JS
- [ ] Python

**Cortana Skills (not tested on Cortana channel)**
- [ ] C#
- [ ] JS
- [ ] Python

**Application Insights**
- [ ] C#
- [ ] JS
- [ ] Python

**Teams**
- [ ] C#
- [ ] JS
- [ ] Python

**Enterprise Bot Template**
- [ ] C#
- [ ] JS
- [ ] Python
