### ISSUE TITLE
4.5 Bot Framework Release Checklist

### ISSUE THREAD

**Issue by CoHealer** [microsoft/botframework-sdk#5455]
## Package Location
C# - [4.5.0-RC3](https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder/4.5.0-RC3)

JS - [4.5.0-rc5](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder/4.5.0-rc5)

Python - https://test.pypi.org/project/botbuilder-core/

## Change Notes
In this release, the team focused on improving and simplifying message and activities handling. The [Bot Framework Activity Schema](https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-activity/botframework-activity.md#conversation-update-activity) is the underlying schema used to define the interaction model for bots. 

Review all changes that went into 4.5 in the detailed change logs:
[[Change Log for .NET](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A4.5+)]   
[[Change Log for Node.js](https://github.com/Microsoft/botbuilder-js/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A4.5+)] 
[[Change Log for Python](https://github.com/Microsoft/botbuilder-python/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A4.5+)]

## GitHub Updates
**Create New Branch** @cleemullins
- [x] C# (https://github.com/Microsoft/botbuilder-dotnet/tree/4.5)
- [x] JS (https://github.com/Microsoft/botbuilder-js/tree/4.5)
- [x] Python (https://github.com/Microsoft/botbuilder-python/tree/4.5)

**Setup Branch Protection on New Branch** @cleemullins
- [x] C#
- [x] JS
- [x] Python

**Bump Version on Master** @cleemullins
- [x] C#
- [x] JS
- [x] Python

**Update Readme.md in master to reflect new branch** @cleemullins
- [x] C#
- [x] JS
- [ ] Python

**Branch Samples** @cleemullins
- [ ] C#
- [ ] JS
- [ ] Python

**Create DRAFT Release** @CoHealer 
- [x] C# (https://github.com/microsoft/botbuilder-dotnet/releases/tag/untagged-c034f3f7020c2d42ac41)
- [x] JS (https://github.com/microsoft/botbuilder-js/releases/tag/untagged-e9552c0abc137b2126c8)
- [x] Python (https://github.com/microsoft/botbuilder-python/releases/tag/untagged-724918ae877c81e81c2f)

**Write release notes and change log** @CoHealer 
- [x] C#
- [x] JS
- [x] Python

**Update road-map** @yochay 
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**Apply Release Notes to DRAFT Release** @CoHealer 
- [x] C#
- [x] JS
- [x] Python

**Publish GitHub Release** @cleemullins 
- [x] C#
- [x] JS
- [ ] Python

## Required Signoff

**Teams**  @CoHealer, Sid Uppal
- [x] C# (Ramjot Singh)
- [x] JS (Robin Liao)

**Cortana** @CoHealer, John Bucy
- [ ] C# (TBD)
- [ ] JS (TBD)

**Virtual Assistant** @CoHealer, Darren Jefford
- [x] C# (Lauren Mills)
- [x] JS (Darren Jefford)

**Emulator @CoHealer, Chris Whitten
- [ ] C# (Chris Whitten) 
- [ ] JS (Chris Whitten)

<a id="testing"></a>
### Testing Status @jwiley84  ###
**Console Adapter**
- [x] C#
- [x] JS
- [x] Python

**Simple Dialog Flow**
- [x] C#
- [x] JS
- [x] Python

**Simple State Management**
- [x] C#
- [x] JS
- [x] Python

**Welcome Messages**
- [x] C#
- [x] JS

**Prompts and Prompt Validations**
- [x] C#
- [x] JS

**Standard Cards**
- [x] C#
- [x] JS
- [x] Python

**Adaptive Cards**
- [x] C#
- [x] JS

**Card Actions**
- [x] C#
- [x] JS
- [x] Python

**Regex Checking**
- [x] C#
- [x] JS

**QnA Maker**
- [x] C#
- [x] JS

**LUIS**
- [x] C#
- [x] JS

**Dispatch**
- [x] C#
- [x] JS

**Attachments**
- [x] C#
- [x] JS

**Proactive Messages**
- [x] C#
- [x] JS

**Middlware**
- [x] C#
- [x] JS

**Translations**
- [x] C#
- [x] JS

**Authentication**
- [x] C#
- [x] JS

**Waterfalls and Dialog Sets**
- [x] C#

**State Storage**
- [x] C#
- [x] JS

**Facebook-specific Events**
- [x] C#
- [x] JS

**Skills (not tested on Cortana channel)**
Tested in VA bot
- [x] C#
- [ ] JS

**Application Insights**
Currently there is no sample that explicitly demonstrates this. Tested via ngrok to deployed bot
- [x] C#
- [x] JS

**Teams**
- [x] C#
- [x] JS

**Enterprise Bot Template**
removed due to VA bot being tested by VA team.

**Comment by cleemullins** [comment]
@RamjotSingh Via Teams

> [1:38 PM] Ramjot Singh
>     consider it green for now
> ​[1:38 PM] Ramjot Singh
>     if something goes sideways I can ping you
>
