### ISSUE TITLE
[Teams] All known Invoke verbs modeled in ActivityHandler

### ISSUE THREAD

**Issue by sgellock** [microsoft/botframework-sdk#5462]
## Issue
We need to evolve our ActivityHandler to account for Invoke verbs issued by Teams

## Proposed change
ActivityHandler should provide first class support for Invoke verbs to support.  Support is required in the C#, JS, and Python SDKs

## Tracking Status
**Dotnet SDK**
- [x] Log tracking issue:  https://github.com/microsoft/botbuilder-dotnet/issues/2244
- [x] PR
- [x] Merged

**Javascript SDK**
- [x] Log tracking issue: https://github.com/microsoft/botbuilder-js/issues/1214 ([~old tracking issue~](https://github.com/microsoft/botbuilder-js/issues/1057))
- [ ] PR
- [ ] Merged

**Java SDK**
- [x] Log tracking issue: https://github.com/microsoft/botbuilder-java/issues/79
- [ ] Tracking issue filed

**Python SDK**
- [x] Log tracking issue:  https://github.com/microsoft/botbuilder-python/issues/257
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by cleemullins** [comment]
C# is done. JS is in progress. Python issue filed. Closing this as it's confusing our issue tracking.
