### ISSUE TITLE
[Teams] Provide a Teams connector that models the standard connector

### ISSUE THREAD

**Issue by sgellock** [microsoft/botframework-sdk#5463]
## Issue
Provide a Teams connector that models the standard connectors

## Proposed change
Teams connector should be discoverable and "reasonably unified" with the SDK's regular connector.  Support is required in the C#, JS, and Python SDKs.

## Tracking Status
**Dotnet SDK**
- [x] Log tracking issue:  https://github.com/microsoft/botbuilder-dotnet/issues/2245
- [x] PR
- [x] Merged

**Javascript SDK**
- [x] Log tracking issue:  https://github.com/microsoft/botbuilder-js/issues/1058
- [ ] PR
- [ ] Merged

**Java SDK**
- [x] Log tracking issue: https://github.com/microsoft/botbuilder-java/issues/80
- [ ] Tracking issue filed

**Python SDK**
- [x] Log tracking issue:  https://github.com/microsoft/botbuilder-python/issues/258
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by cleemullins** [comment]
C# is done. JS is in progress. Pythong is logged. Closing this, as it's causing counting / tracking confusion.
