### ISSUE TITLE
v4.5.0b4 Bot Framework (Python) Minor Release Checklist

### ISSUE THREAD

**Issue by CoHealer** [microsoft/botframework-sdk#5492]
## Package Location
Python - https://test.pypi.org/project/botbuilder-core/

## Change Notes
In this release, the team focused on improving code quality via bug fixes as well as working towards feature parity with botbuilder-dotnet. The [Bot Framework Activity Schema](https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-activity/botframework-activity.md#conversation-update-activity) is the underlying schema used to define the interaction model for bots. 

Review all changes that went into 4.5.0b4 in the detailed change logs:
[[Change Log for Python]](https://github.com/microsoft/botbuilder-python/pulls?utf8=✓&q=is%3Apr+number%3A275+or+272+or+271+or+276+or+264+or+280+or+279+or+285+or+278+or+287+or+290+or+291+or+289+or+284+or+282+or+293+or+294+or+295+or+296+)

## GitHub Updates
**Create New Branch** @cleemullins
- [x] Python (https://github.com/microsoft/botbuilder-python/tree/4.5b4)

**Setup Branch Protection on New Branch** @cleemullins
- [x] Python

**Bump Version on Master** @cleemullins
- [x] Python   [Not Needed. Master is 4.6-Preview]

**Create DRAFT Release** @CoHealer 
- [x] https://github.com/microsoft/botbuilder-python/releases/edit/untagged-3014b3ad5f350f6bf1cc)

**Write release notes and change log** @CoHealer 
- [x] Python

**Apply Release Notes to DRAFT Release** @CoHealer 
- [x] Python

**Publish GitHub Release** @cleemullins 
- [x] Python

<a id="testing"></a>
### Testing Status @jwiley84  ###
**Console Adapter**
- [x] Python

**Simple Dialog Flow**
- [x] Python

**Simple State Management**
- [x] Python

**Standard Cards**
- [x] Python

**LUIS**
- [x] Python

**App Insights**
- [x] Python

**Comment by jwiley84** [comment]
Testing complete!

**Comment by jwiley84** [comment]
Application Insights was fixed by Axel, NOW testing is done! All good to go, no issues.

**Comment by cleemullins** [comment]
We are done, and packages are released. Closing this out.
