### ISSUE TITLE
Bot Framework 4.6 Release Checklist

### ISSUE THREAD

**Issue by CoHealer** [microsoft/botframework-sdk#5639]
## Package Location
https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily
https://botbuilder.myget.org/gallery/botbuilder-v4-js-daily
https://botbuilder.myget.org/gallery/botframework-cli
https://test.pypi.org/project/botbuilder-core/

## GitHub Updates
**Create New Branch** @cleemullins
- [x] C# (https://github.com/Microsoft/botbuilder-dotnet/tree/4.6)
- [x] JS (https://github.com/Microsoft/botbuilder-js/tree/4.6)
- [x] Python (https://github.com/Microsoft/botbuilder-python/tree/4.6)
- [x] BF-Cli (https://github.com/Microsoft/botframework-cli/tree/4.6)

**Setup Branch Protection on New Branch** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] BF-Cli

**Bump Version on Master** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] BF-Cli

**Update Readme.md in master to reflect new branch** @cleemullins
- [ ] C#
- [x] JS
- [x] Python
- [x] bf-cli

**Branch Samples** @cleemullins
- [ ] C#
- [ ] JS
- [ ] Python

**Create DRAFT Release** @cleemullins
- [x] C# (https://github.com/microsoft/botbuilder-dotnet/releases/tag/untagged-b371591ff2db1615f3c4)
- [x] JS (https://github.com/microsoft/botbuilder-js/releases/tag/untagged-aa8812c5f9bae166f699)
- [x] Python (https://github.com/Microsoft/botbuilder-python/releases/edit/untagged-guid)
- [x] bf-cli (https://github.com/microsoft/botframework-cli/releases/edit/untagged-0c35b42fdcb460190c01)

**Consolidate release notes and change logs ** @CoHealer 
- [x] C#
- [x] JS
- [x] Python
- [x] bf-cli

**Apply Release Notes to DRAFT Release** @CoHealer 
- [x] C#
- [x] JS
- [x] Python
- [x] bf-cli

**Publish GitHub Release** @cleemullins 
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] bf-cli

## Required Signoff

**Teams**  Sid Uppal, Andrew Clear
- [X] C# (Ramjot Singh)
- [X] JS (Robin Liao)

**CCI** Salem Bacha, Karthik Narayanan
- [x] C# 
- [x] JS 

**Cortana** Vivek Goswami
- [x] C#
- [x] JS 
- [ ] Python

**Virtual Assistant** Darren Jefford
- [x] C# 
- [x] JS
- [ ] bf-cli

**Emulator** Chris Whitten
- [ ] C# (Chris Whitten) 
- [ ] JS (Chris Whitten)
- [ ] Python (TBD)

## Testing Status 
**Acceptance testing:** @jwiley84, @stevkan 

**Console Adapter**
- [x] C#
- [x] JS
- [x] Python

**Simple Dialog Flow**
- [x] C#
- [x] JS
- [x] Python

**Simple State Management**
- [x] C#
- [x] JS
- [x] Python

**Welcome Messages**
- [x] C#
- [x] JS
- [x] Python

**Prompts and Prompt Validations**
- [x] C#
- [x] JS
- [ ] Python

**Standard Cards**
- [x] C#
- [x] JS
- [ ] Python

**Adaptive Cards**
- [x] C#
- [x] JS
- [ ] Python

**Card Actions**
- [x] C#
- [x] JS
- [ ] Python

**Regex Checking**
- [x] C#
- [x] JS
- [ ] Python

**QnA Maker**
- [x] C#
- [x] JS
- [ ] Python

**LUIS**
- [x] C#
- [x] JS
- [x] Python

**Dispatch**
- [x] C#
- [x] JS
- [ ] Python

**Attachments**
- [x] C#
- [x] JS
- [ ] Python

**Proactive Messages**
- [x] C#
- [x] JS
- [ ] Python

**Middlware**
- [x] C#
- [x] JS
- [ ] Python

**Translations**
- [x] C#
- [x] JS
- [ ] Python

**Authentication**
- [x] C#
- [x] JS
- [ ] Python

**Waterfalls and Dialog Sets**
- [x] C#

**State Storage**
- [x] C#
- [x] JS
- [ ] Python

**Transcript Logging**
- [ ] C#
- [ ] JS
- [ ] Python

**Facebook-specific Events**
- [x] C#
- [x] JS
- [ ] Python

**Cortana Skills (not tested on Cortana channel)**
- [ ] C#
- [ ] JS
- [ ] Python

**Application Insights**
- [x] C#
- [ ] JS
- [ ] Python

**Teams**
- [ ] C#
- [ ] JS
- [ ] Python

**Enterprise Bot Template**
- [ ] C#
- [ ] JS
- [ ] Python

**BF-CLI**
- [x] Global & config
- [x] Chatdown
- [x] Luis
- [x] QnAMaker

**Comment by yochay** [comment]
@cleemullins for PVA (4.6 only) please get a signoff from Salem and Karthik
