### ISSUE TITLE
Add support for skill OAuthCard to Emulator and WebChat

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#5654]
Currently the emulator and webchat receive an OAuthCard from the bot and they create and update the card with a sign in link they generate that allows them to bypass the magic code prompt. 

This link is generated based on the AppId of the host bot and that allows the token service to post back an event activity with name "tokens/response" that contains the generated token to the parent bot.

The issue is that for skills, the Emulator and WebChat don't have the AppId of the skill and it doesn't know how to render a link that will post back to the skill and not the parent bot.

We may need to add an attribute to the OAuth card with the AppId of the skill or think of another mechanism to support bypassing the magic code for skill OAuthCards in webchat and emulator. As an alternative, we can explore generating the link for the card in the bot like we do for Teams and other channels and update webchat and emulator to work with these cards.

This issue involves:

- [x] Adding support to **Emulator** to render OAuthCards for skills without having to use magic number (tracked in the Emulator [issue 1940](https://github.com/microsoft/BotFramework-Emulator/issues/1940).
- [x] Adding support to **WebChat** to render OAuthCards for skills without having to use magic number (tracked in the WebChat [issue 2494](https://github.com/microsoft/BotFramework-Emulator/issues/2494)..
- [x] Updating the **OAuthCardPrompt in the SDK** to take the parameters needed to allow skills OAuth cards to render and work with the Emulator and WebChat.
   - [x] DotNet (tracked in [2851](https://github.com/microsoft/botbuilder-dotnet/issues/2851))
   - [x] JavaScript (tracked in [1662](https://github.com/microsoft/botbuilder-js/issues/1662))
   - [x] Python (tracked in [698](https://github.com/microsoft/botbuilder-python/issues/698))

**Comment by gabog** [comment]
All child issues are closed, closing this one too
