### ISSUE TITLE
Bot Framework R7 Release Checklist

### ISSUE THREAD

**Issue by CoHealer** [microsoft/botframework-sdk#5686]
## Package Location
https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily
https://botbuilder.myget.org/gallery/botbuilder-v4-js-daily
https://botbuilder.myget.org/gallery/botframework-cli
https://test.pypi.org/project/botbuilder-core

## GitHub Updates
**Create New Branch** @cleemullins
- [x] C# (https://github.com/Microsoft/botbuilder-dotnet/tree/4.7)
- [x] JS (https://github.com/Microsoft/botbuilder-js/tree/4.7)
- [x] Python (https://github.com/Microsoft/botbuilder-python/tree/4.7)
- [x] BF-Cli (https://github.com/Microsoft/botframework-cli/tree/4.7)

**Setup Branch Protection on New Branch** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] BF-Cli

**Bump Version on Master** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] BF-Cli

**Update Readme.md in master to reflect new branch** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] bf-cli

**Branch Samples** @cleemullins
- [x] C#
- [x] JS
- [x] Python

**Create DRAFT Release** @cleemullins
- [x] C# (https://github.com/microsoft/botbuilder-dotnet/releases/tag/untagged-692f087f3956d9035ee3)
- [x] JS (https://github.com/microsoft/botbuilder-js/releases/tag/untagged-9273af39d0a06648261d)
- [x] Python (https://github.com/microsoft/botbuilder-python/releases/tag/untagged-15cdf783d998a6067f4a)
- [x] bf-cli (https://github.com/microsoft/botframework-cli/releases/tag/untagged-43398cdc886fc6e43f61)

**Consolidate release notes and change logs ** @christopheranderson, @axelsrz
- [x] C#
- [x] JS
- [x] Python
- [x] bf-cli

**Apply Release Notes to DRAFT Release** @christopheranderson  , @axelsrz
- [ ] C#
- [x] JS
- [ ] Python
- [ ] bf-cli

**Publish GitHub Release** @cleemullins 
- [x] C#
- [x] JS
- [x] Python
- [x] bf-cli

## Required Signoff

**Teams**  Sid Uppal, Andrew Clear
- [ ] C# (Ramjot Singh)
- [ ] JS (Robin Liao)

**CCI** Salem Bacha, Karthik Narayanan
- [ ] C# 
- [ ] JS 

**Cortana** Vivek Goswami
- [ ] C#
- [ ] JS 
- [ ] Python

**Virtual Assistant** Darren Jefford
- [x] C# 
- [x] JS
- [x] bf-cli

**Emulator** Chris Whitten
- [x] C# (Chris Whitten) 
- [x] JS (Chris Whitten)
- [ ] Python (TBD)

## Testing Status 
**Acceptance testing:** @jwiley84, @stevkan 

**Console Adapter**
- [x] C#
- [x] JS
- [x] Python

**Simple Dialog Flow**
- [x] C#
- [x] JS
- [x] Python

**Simple State Management**
- [x] C#
- [x] JS
- [x] Python

**Welcome Messages**
- [x] C#
- [x] JS
- [x] Python

**Prompts and Prompt Validations**
- [x] C#
- [x] JS
- [x] Python

**Standard Cards**
- [x] C#
- [x] JS
- [x] Python

**Adaptive Cards**
- [x] C#
- [x] JS
- [x] Python

**Card Actions**
- [x] C#
- [x] JS
- [x] Python

**Regex Checking**
- [x] C#
- [x] JS
- [x] Python

**QnA Maker**
- [x] C#
- [x] JS
- [x] Python

**LUIS**
- [x] C#
- [x] JS
- [x] Python

**Dispatch**
- [x] C#
- [x] JS
- [x] Python

**Attachments**
- [x] C#
- [x] JS
- [x] Python

**Proactive Messages**
- [x] C#
- [x] JS
- [x] Python

**Middlware**
- [x] C#
- [x] JS
- [x] Python

**Translations**
- [x] C#
- [x] JS
- [x] Python

**Authentication**
- [x] C#
- [x] JS
- [x] Python

**Waterfalls and Dialog Sets**
- [x] C#

**State Storage**
- [x] C#
- [x] JS
- [x] Python

**Transcript Logging**
- [x] C#
- [x] JS
- [x] Python

**Facebook-specific Events**
- [x] C#
- [x] JS
- [x] Python

**Cortana Skills (not tested on Cortana channel)**
- [x] C#
- [x] JS
- [x] Python

**Application Insights**
- [x] C#
- [x] JS
- [x] Python

**Teams**
- [x] C#
- [x] JS
- [x] Python

**Enterprise Bot Template**
- [x] C#
- [x] JS
- [x] Python

**BF-CLI**
- [x] Global & config
- [x] Chatdown
- [x] Luis
- [x] QnAMaker
