### ISSUE TITLE
Bot Framework SDK R8 Release Checklist

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#5769]
## Package Location
https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily
https://botbuilder.myget.org/gallery/botbuilder-v4-js-daily
https://botbuilder.myget.org/gallery/botframework-cli
https://test.pypi.org/project/botbuilder-core
https://www.nuget.org/packages/Microsoft.Bot.Builder/3.30.0 (v3.30.0)
https://www.npmjs.com/package/botbuilder/v/3.30.0 (v3.30.0)

## GitHub Updates
**Create New Branch** @cleemullins
- [x] C# [4.8 Branch Created](https://github.com/microsoft/botbuilder-dotnet/tree/4.8)
- [x] JS 
- [x] Python 
- [x] BF-Cli 
- [x] V3 C# & JS [3.30 branch created](https://github.com/microsoft/BotBuilder-V3/tree/3.30)

**Setup Branch Protection on New Branch** @cleemullins
- [x] C# (Done)
- [x] JS
- [x] Python
- [x] BF-Cli
- [x] V3 C# & JS

**Bump Version on Master** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] BF-Cli
- [X] V3 C# & JS

**Update Readme.md in master to reflect new branch** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] bf-cli
- [ ] V3 C# & JS

**Branch Samples** @cleemullins
- [x] C#
- [x] JS
- [ ] Python

**Create DRAFT Release** @cleemullins
- [x] C#  [DRAFT Release found here](https://github.com/microsoft/botbuilder-dotnet/releases/edit/untagged-b062c03819460cb7980c)
- [x] JS [DRAFT Release found here](https://github.com/microsoft/botbuilder-js/releases/edit/untagged-aecbcea6858bd27b1152)
- [x] Python [DRAFT Release found here](https://github.com/microsoft/botbuilder-python/releases/edit/untagged-620ee0a11c4d6e955f3a)
- [x] bf-cli [DRAFT Release found here](https://github.com/microsoft/botframework-cli/releases/edit/untagged-1c802ad98c24e96e521d)
- [x] v3 SDK [DRAFT Release Found here](https://github.com/microsoft/BotBuilder-V3/releases/edit/untagged-f93301abe3de55a3b23d)

**Consolidate release notes and change logs** @christopheranderson, @axelsrz
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] bf-cli

**Apply Release Notes to DRAFT Release** @christopheranderson  , @axelsrz
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] bf-cli

**Publish GitHub Release** @cleemullins 
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] bf-cli
- [ ] V3 C#
- [ ] V3 JS

## Required Signoff

**Teams**  Sid Uppal, Andrew Clear
- [ ] C# (Ramjot Singh)
- [ ] JS (Robin Liao)

**PVA** Pawan Taparia, Salem Bacha, Karthik Narayanan
- [ ] C# 
- [ ] JS 

**Cortana** Vivek Goswami
- [ ] C#
- [ ] JS 
- [ ] Python

**Virtual Assistant** Darren Jefford
- [ ] C# 
- [ ] JS
- [ ] bf-cli

**Emulator** Chris Whitten
- [ ] C# (Chris Whitten) 
- [ ] JS (Chris Whitten)
- [ ] Python (TBD)

## Testing Status 
**Acceptance testing:** @jwiley84, @stevkan 

**Console Adapter**
- [ ] C#
- [ ] JS
- [ ] Python

**Simple Dialog Flow**
- [ ] C#
- [ ] JS
- [ ] Python

**Simple State Management**
- [ ] C#
- [ ] JS
- [ ] Python

**Welcome Messages**
- [ ] C#
- [ ] JS
- [ ] Python

**Prompts and Prompt Validations**
- [ ] C#
- [ ] JS
- [ ] Python

**Standard Cards**
- [ ] C#
- [ ] JS
- [ ] Python

**Adaptive Cards**
- [ ] C#
- [ ] JS
- [ ] Python

**Card Actions**
- [ ] C#
- [ ] JS
- [ ] Python

**Regex Checking**
- [ ] C#
- [ ] JS
- [ ] Python

**QnA Maker**
- [ ] C#
- [ ] JS
- [ ] Python

**LUIS**
- [ ] C#
- [ ] JS
- [ ] Python

**Dispatch**
- [ ] C#
- [ ] JS
- [ ] Python

**Attachments**
- [ ] C#
- [ ] JS
- [ ] Python

**Proactive Messages**
- [ ] C#
- [ ] JS
- [ ] Python

**Middlware**
- [ ] C#
- [ ] JS
- [ ] Python

**Translations**
- [ ] C#
- [ ] JS
- [ ] Python

**Authentication**
- [ ] C#
- [ ] JS
- [ ] Python

**Waterfalls and Dialog Sets**
- [ ] C#

**State Storage**
- [ ] C#
- [ ] JS
- [ ] Python

**Transcript Logging**
- [ ] C#
- [ ] JS
- [ ] Python

**Facebook-specific Events**
- [ ] C#
- [ ] JS
- [ ] Python

**Cortana Skills (not tested on Cortana channel)**
- [ ] C#
- [ ] JS
- [ ] Python

**Application Insights**
- [ ] C#
- [ ] JS
- [ ] Python

**Teams**
- [ ] C#
- [ ] JS
- [ ] Python

**Enterprise Bot Template**
- [ ] C#
- [ ] JS
- [ ] Python

**BF-CLI**
- [ ] Global & config
- [ ] Chatdown
- [ ] Luis
- [ ] QnAMaker

## Release Schedule

| **Due Dates** | **Stage**                                                  | **BF Owner**  | **Status** | **Artifacts**  **(links to docs,  build,drops, etc)** | **Signed Off**  (see partners) |
| ------------- | ---------------------------------------------------------- | ------------- | ---------- | ----------------------------------------------------- | ------------------------------ |
| 3/4           | Notification to partners  (ask:ack)                        | Kamran        | TBD        |                                                       |                                |
| 3/9           | GA:SDK V4.8 RC0 release                                    | Chris Mullins | TBD        |                                                       |                                |
| 3/9           | GA:SDK V4.8 RC0  stabilization: bug bash, test             | Chris Mullins | TBD        |                                                       |                                |
| 3/10          | GA:SDK V4.8 RC0 handoff to  partners for validation        | Chris Mullins | TBD        |                                                       |                                |
| 3/12          | GA:SDK V4.8 partners validation response handshake         | Kamran        | TBD        |                                                       |                                |
| 3/10 - 3/16   | GA:SDK V4.8 RC1-n cycle: release to test validation        | Chris Mullins | TBD        |                                                       |                                |
| 3/16          | GA:SDK V4.8 Final handoff to partners validation handshake | Chris Mullins | TBD        |                                                       |                                |
| 3/16          | GA:SDK V4.8 Final Release                                  | Chris Mullins | TBD        |                                                       |                                |
