### ISSUE TITLE
Bot Framework SDK R9 Checklist

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#5802]
## Package Location
https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily
https://botbuilder.myget.org/gallery/botbuilder-v4-js-daily
https://botbuilder.myget.org/gallery/botbuilder-v4-java-daily
https://botbuilder.myget.org/gallery/botframework-cli [4.9.0](https://botbuilder.myget.org/feed/botframework-cli/package/npm/@microsoft/botframework-cli/4.9.0-RC0)
https://test.pypi.org/project/botbuilder-core
https://www.nuget.org/packages/Microsoft.Bot.Builder/3.30.0 (v3.30.0)
https://www.npmjs.com/package/botbuilder/v/3.30.0 (v3.30.0)

## GitHub Updates
**Create New Branch** @cleemullins
- [x] C# 
- [x] JS 
- [x] Python 
- [x] Java 
- [x] BF-Cli 4.9
- [x] V3 C# & JS - No changes to v3 are needed. 3.30 is already released.

**Setup Branch Protection on New Branch** @cleemullins
- [x] C# (Done)
- [x] JS
- [x] Python
- [x] Java 
- [x] BF-Cli

**Bump Version on Master** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] BF-Cli

**Update Readme.md in master to reflect new branch** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

**Branch Samples** @cleemullins
- [x] C#
- [x] JS
- [x] Python

**Create DRAFT Release** @cleemullins
- [x] C# [4.9 DRAFT Release](https://github.com/microsoft/botbuilder-dotnet/releases/edit/untagged-59a333705937954dec27) 
- [x] JS [4.9 DRAFT Release](https://github.com/microsoft/botbuilder-js/releases/edit/untagged-d05c53913375580ca877)
- [x] Python [4.9 DRAFT Release](https://github.com/microsoft/botbuilder-python/releases/tag/untagged-652dc67cce30a2479fab)
- [x] Java [4.6.0-preview4 DRAFT Release](https://github.com/microsoft/botbuilder-java/releases/tag/untagged-bf7b80e12f4633135f14)
- [x] bf-cli [4.9 DRAFT Release](https://github.com/microsoft/botframework-cli/releases/edit/untagged-732df86d80103e2ccdf1)

**Consolidate release notes and change logs** @christopheranderson, @axelsrz
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

**Apply Release Notes to DRAFT Release** @christopheranderson  , @axelsrz
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

**Publish GitHub Release** @cleemullins 
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

## Required Signoff

**Teams**  Sid Uppal, Andrew Clear
- [ ] C# (Ramjot Singh)
- [ ] JS (Robin Liao)

**PVA** Pawan Taparia, Salem Bacha, Karthik Narayanan
- [x] C# 
- [x] JS 

**Cortana** Vivek Goswami
- [ ] C#
- [ ] JS 
- [ ] Python

**Virtual Assistant** Darren Jefford
- [x] C# 
- [ ] JS
- [x] bf-cli

**Emulator** Chris Whitten
- [x] C# (Chris Whitten) 
- [ ] JS (Chris Whitten)
- [ ] Python (TBD)

## Testing Status 
**Acceptance testing:** @jwiley84, @stevkan 

**Step Into Debugging**
- [ ] C#
- [ ] JS
- [x] Python

**Console Adapter**
- [ ] C#
- [ ] JS
- [x] Python

**Simple Dialog Flow**
- [ ] C#
- [ ] JS
- [x] Python

**Simple State Management**
- [ ] C#
- [ ] JS
- [x] Python
- [x] Java

**Welcome Messages**
- [ ] C#
- [ ] JS
- [x] Python
- [x] Java

**Prompts and Prompt Validations**
- [ ] C#
- [ ] JS
- [x] Python

**Standard Cards**
- [ ] C#
- [ ] JS
- [x] Python

**Adaptive Cards**
- [ ] C#
- [ ] JS
- [x] Python

**Card Actions**
- [ ] C#
- [ ] JS
- [x] Python

**Regex Checking**
- [ ] C#
- [ ] JS
- [x] Python

**QnA Maker**
- [ ] C#
- [ ] JS
- [x] Python

**LUIS**
- [ ] C#
- [ ] JS
- [x] Python

**Dispatch**
- [ ] C#
- [ ] JS
- [x] Python

**Attachments**
- [ ] C#
- [ ] JS
- [x] Python

**Proactive Messages**
- [ ] C#
- [ ] JS
- [x] Python
- [x] Java

**Middlware**
- [ ] C#
- [ ] JS
- [x] Python

**Translations**
- [ ] C#
- [ ] JS
- [x] Python

**Authentication**
- [ ] C#
- [ ] JS
- [x] Python

**Waterfalls and Dialog Sets**
- [ ] C#

**State Storage**
- [ ] C#
- [ ] JS
- [x] Python

**Transcript Logging**
- [ ] C#
- [ ] JS
- [x] Python

**Facebook-specific Events**
- [ ] C#
- [ ] JS
- [x] Python

**Cortana Skills (not tested on Cortana channel)**
- [ ] C#
- [ ] JS
- [ ] Python

**Application Insights**
- [ ] C#
- [ ] JS
- [x] Python

**Teams**
- [ ] C#
- [ ] JS
- [x] Python
- [x] Java

**Enterprise Bot Template**
- [ ] C#
- [ ] JS
- [ ] Python

**BF-CLI**
- [x] Global & config
- [x] Chatdown
- [x] Luis
- [x] QnAMaker

**Comment by cleemullins** [comment]
Release of primary SDK is done. Now it's on to Samples, Docs, and Code Generators.
