### ISSUE TITLE
Bot Framework SDK R10 Release Checklist

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#5979]
## Package Location
* C# (rc1)
** https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily
** https://dev.azure.com/ConversationalAI/BotFramework/_packaging?_a=feed&feed=SDK

* JS (Uses the @rc tag on public NPM)
** https://www.npmjs.com/package/botbuilder

* Python
** https://test.pypi.org/project/botbuilder-core/4.10.0rc0/

* BF CLI (Uses the @rc tag on public NPM)
** https://www.npmjs.com/package/@microsoft/botframework-cli

* JAVA
** https://search.maven.org/search?q=com.microsoft.bot

## GitHub Updates
**Create New Branch** @cleemullins
- [x] C# 
- [x] JS 
- [x] Python 
- [x] Java 
- [x] BF-Cli
- [X] V3 C# & JS - No changes to v3 are needed. 3.30 is already released.

**Setup Branch Protection on New Branch** @cleemullins
- [x] C# (Done)
- [x] JS
- [x] Python
- [x] Java 
- [x] BF-Cli

**Bump Version on Master** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [ ] BF-Cli

**Update Readme.md in master to reflect new branch** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [ ] bf-cli

**Branch Samples** @cleemullins
- [ ] C#
- [ ] JS
- [ ] Python

**Create DRAFT Release** @cleemullins
- [x] C# [4.10 DRAFT Release](https://github.com/microsoft/botbuilder-dotnet/releases/edit/untagged-cc1ae2e300be11ece065) 
- [x] JS [4.10 DRAFT Release](https://github.com/microsoft/botbuilder-js/releases/edit/untagged-175ab018534a5ca6714d)
- [x] Python [4.10 DRAFT Release](https://github.com/microsoft/botbuilder-python/releases/edit/untagged-2683203a3805c6574601)
- [x] Java [4.6-preview6 Release](https://github.com/microsoft/botbuilder-java/releases/tag/untagged-cf99c0031662eb4b0386)
- [x] bf-cli [4.10 DRAFT Release](https://github.com/microsoft/botframework-cli/releases/edit/untagged-d02bacc53fe61113dea4)
- [x] BotFramework-SDK [4.10 Release](https://github.com/microsoft/botframework-sdk/releases/tag/4.10)

**Consolidate release notes and change logs** @cleemullins, @axelsrz
- [x] C#
- [x] JS
- [x] Python
- [ ] Java 
- [x] bf-cli

**Apply Release Notes to DRAFT Release** @cleemullins, @axelsrz
- [x] C#
- [x] JS
- [x] Python
- [ ] Java 
- [x] bf-cli

**Publish GitHub Release** @cleemullins 
- [x] C#
- [x] JS
- [x] Python
- [ ] Java 
- [x] bf-cli

## Required Signoff

**Teams**  Sid Uppal, Andrew Clear
- [ ] C# (Ramjot Singh)
- [ ] JS (Robin Liao)

**PVA** Pawan Taparia, Salem Bacha, Karthik Narayanan
- [ ] C# 
- [ ] JS 

**Cortana** Vivek Goswami
- [ ] C#
- [ ] JS 
- [ ] Python

**Virtual Assistant** Darren Jefford / Ted Li / 
- [ ] C# 
- [ ] JS
- [ ] bf-cli

**Emulator** Chris Whitten
- [ ] C# (Chris Whitten) 
- [ ] JS (Chris Whitten)
- [ ] Python (TBD)

## Testing Status 
**Acceptance testing:** @jwiley84, @stevkan 

**Orchestrator Package Works** @vishwacsena 
- [ ] C#
- [ ] JS

**New Azure Blobs package works** @EricDahlvang 
- [x] C#
- [x] JS

**Step Into Debugging**
- [x] C#
- [x] JS
- [x] Python

**Console Adapter**
- [x] C#
- [x] JS
- [x] Python

**Simple Dialog Flow**
- [x] C#
- [x] JS
- [x] Python

**Simple State Management**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Welcome Messages**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Prompts and Prompt Validations**
- [x] C#
- [x] JS
- [x] Python

**Standard Cards**
- [x] C#
- [x] JS
- [x] Python

**Adaptive Cards**
- [x] C#
- [x] JS
- [x] Python

**Card Actions**
- [x] C#
- [x] JS
- [x] Python

**Regex Checking**
- [x] C#
- [x] JS
- [x] Python

**QnA Maker**
- [x] C#
- [x] JS
- [x] Python

**LUIS**
- [x] C#
- [x] JS
- [x] Python

**Dispatch**
- [x] C#
- [x] JS
- [x] Python

**Attachments**
- [x] C#
- [x] JS
- [x] Python

**Proactive Messages**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Middleware**
- [x] C#
- [x] JS
- [x] Python

**Translations**
- [x] C#
- [x] JS
- [x] Python

**Authentication**
- [x] C#
- [x] JS
- [x] Python

**Waterfalls and Dialog Sets**
- [x] C#

**State Storage**
- [x] C#
- [x] JS
- [x] Python

**Transcript Logging**
- [ ] C#
- [ ] JS
- [ ] Python

**Facebook-specific Events**
- [x] C#
- [x] JS
- [x] Python

**Cortana Skills (not tested on Cortana channel)**
- [ ] C#
- [ ] JS
- [ ] Python

**Application Insights**
- [x] C#
- [x] JS
- [x] Python

**Teams**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Enterprise Bot Template**
- [ ] C#
- [ ] JS
- [ ] Python

**BF-CLI**
- [x] Global & config
- [x] Chatdown
- [x] Luis
- [x] QnAMaker
