### ISSUE TITLE
R11 Release Checklist

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#6086]
## Package Location
* C# 
** [4.11.0](https://dev.azure.com/ConversationalAI/BotFramework/_packaging?_a=package&feed=SDK&package=Microsoft.Bot.Builder&protocolType=NuGet&version=4.11.0&view=overview)
* JS (Uses the @rc tag on public NPM)
** [4.11.0](https://www.npmjs.com/package/botbuilder/v/4.11.0)
** https://www.npmjs.com/package/botbuilder
* Python
** https://test.pypi.org/project/botbuilder-core/4.11.0rc1/
* BF CLI (Uses the @rc tag on public NPM)
** https://www.npmjs.com/package/@microsoft/botframework-cli
** https://www.npmjs.com/package/@microsoft/botframework-cli/v/4.11.0
* JAVA
** https://search.maven.org/search?q=g:com.microsoft.bot%20AND%20v:4.6.0-preview7
* Web Chat
   - CDN (targeting 11/5 morning to noon)
      - https://cdn.botframework.com/botframework-webchat/4.11.0/webchat.js ([webchat-es5.js](https://cdn.botframework.com/botframework-webchat/4.11.0/webchat-es5.js)) ([webchat-minimal.js](https://cdn.botframework.com/botframework-webchat/4.11.0/webchat-minimal.js))
   - NPM (released on 11/4) : https://www.npmjs.com/package/botframework-webchat/v/4.11.0
   - Daily build (for RC)
      - https://github.com/microsoft/BotFramework-WebChat/releases/daily

## GitHub Updates
**Create New Branch** @cleemullins
- [x] C# [4.11](https://github.com/microsoft/botbuilder-dotnet/tree/4.11)
- [x] JS [4.11](https://github.com/microsoft/botbuilder-js/tree/4.11)
- [x] Python [4.11](https://github.com/microsoft/botbuilder-python/tree/4.11)
- [x] Java  [4.7-preview7](https://github.com/microsoft/botbuilder-java/tree/4.6-preview7)
- [x] BF-Cli [4.11](https://github.com/microsoft/botframework-cli/tree/4.11)
- [x] V3 C# & JS - No changes to v3 are needed. 3.30 is already released.

**Setup Branch Protection on New Branch** @cleemullins
- [x] C# (Done)
- [x] JS
- [x] Python
- [x] Java 
- [x] BF-Cli

**Bump Version on Master** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] BF-Cli

**Update Readme.md in master to reflect new branch** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli (No updates to make)

**Branch Samples** @cleemullins
- [x] C#
- [x] JS
- [x] Python

**Create DRAFT Release** @cleemullins
- [x] C# [4.11 DRAFT Release]() 
- [x] JS [4.11 DRAFT Release]() 
- [x] Python [4.11 DRAFT Release](https://github.com/microsoft/botbuilder-python/releases/tag/untagged-7c5f90eaa012892ad009) 
- [x] Java [4.6-preview7 DRAFT Release](https://github.com/microsoft/botbuilder-java/releases/tag/untagged-b9ae588dd5414b45deb6) 
- [x] bf-cli [4.11 DRAFT Release](https://github.com/microsoft/botframework-cli/releases/edit/untagged-63d6623f9310c79d33e9) 
- [x] BotFramework-SDK [4.11 DRAFT Release](https://github.com/microsoft/botframework-sdk/releases/edit/untagged-399e8d235cb97eef02ce) 

**Consolidate release notes and change logs** @cleemullins, @EricDahlvang
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

**Apply Release Notes to DRAFT Release** @cleemullins, @EricDahlvang
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

**Publish GitHub Release** @EricDahlvang
- [x] C#
- [x] JS
- [x] Python
- [ ] Java 
- [x] bf-cli

**Web Chat** @compulim
- [x] https://github.com/microsoft/BotFramework-WebChat/issues/3566
   - [Release testing page](https://corinagum.github.io/WebChat-release-testing)
   - [Daily build](https://github.com/microsoft/BotFramework-WebChat/releases/daily)
   - [x] Published to NPM: https://www.npmjs.com/package/botframework-webchat/v/4.11.0
   - [x] Published to CDN: https://cdn.botframework.com/botframework-webchat/4.11.0/webchat.js ([webchat-es5.js](https://cdn.botframework.com/botframework-webchat/4.11.0/webchat-es5.js)) ([webchat-minimal.js](https://cdn.botframework.com/botframework-webchat/4.11.0/webchat-minimal.js))

## Required Signoff

**Teams**  Sid Uppal, Andrew Clear
- [x] C# (Ramjot Singh)
- [x] JS (Robin Liao)

**PVA** Pawan Taparia, Salem Bacha, Karthik Narayanan
- [ ] C# 
- [ ] JS 

**Cortana** Vivek Goswami
- [ ] C#
- [ ] JS 
- [ ] Python

**Virtual Assistant** Darren Jefford / Ted Li / 
- [ ] C# 
- [ ] JS
- [ ] bf-cli

**Emulator** Chris Whitten
- [ ] C# (Chris Whitten) 
- [ ] JS (Chris Whitten)
- [ ] Python (TBD)

## Testing Status 
**Acceptance testing:** @jwiley84, @stevkan 

**Orchestrator Package Works**
- [ ] C#
- [ ] JS

**New Azure Blobs package works** @EricDahlvang 
- [ ] C#
- [ ] JS

**Step Into Debugging**
- [x] C#
- [x] JS
- [x] Python

**Console Adapter**
- [x] C#
- [x] JS
- [x] Python

**Simple Dialog Flow**
- [x] C#
- [x] JS
- [x] Python

**Simple State Management**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Welcome Messages**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Prompts and Prompt Validations**
- [x] C#
- [x] JS
- [x] Python

**Standard Cards**
- [x] C#
- [x] JS
- [x] Python

**Adaptive Cards**
- [x] C#
- [x] JS
- [x] Python

**Card Actions**
- [x] C#
- [x] JS
- [x] Python

**Regex Checking**
- [x] C#
- [x] JS
- [x] Python

**QnA Maker**
- [x] C#
- [x] JS
- [x] Python

**LUIS**
- [x] C#
- [x] JS
- [x] Python

**Dispatch**
- [x] C#
- [x] JS
- [x] Python

**Attachments**
- [x] C#
- [x] JS
- [x] Python

**Proactive Messages**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Middleware**
- [x] C#
- [x] JS
- [x] Python

**Translations**
- [x] C#
- [x] JS
- [x] Python

**Authentication**
- [x] C#
- [x] JS
- [x] Python

**Waterfalls and Dialog Sets**
- [x] C#

**State Storage**
- [x] C#
- [x] JS
- [x] Python

**Transcript Logging**
- [x] C#
- [x] JS
- [x] Python

**Facebook-specific Events**
- [x] C#
- [x] JS
- [x] Python

**Application Insights**
- [x] C#
- [x] JS
- [x] Python

**Teams**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Enterprise Bot Template**
- [ ] C#
- [ ] JS
- [ ] Python

**BF-CLI**
- [ ] Global & config
- [ ] Chatdown
- [ ] Luis
- [ ] QnAMaker
