### ISSUE TITLE
R12 Release Checklist

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#6200]
## Package Location
* C# 
** [4.12.0]()
* JS (Uses the @rc tag on public NPM)
** [4.12.0](https://www.npmjs.com/package/botbuilder/v/4.12.0)
** https://www.npmjs.com/package/botbuilder
* Python
** https://test.pypi.org/project/botbuilder-core/4.12.0/
* BF CLI (Uses the @rc tag on public NPM)
** https://www.npmjs.com/package/@microsoft/botframework-cli
** https://www.npmjs.com/package/@microsoft/botframework-cli/v/4.12.0
* JAVA
** https://oss.sonatype.org/#nexus-search;quick~com.microsoft.bot
* Web Chat
  * [ ] CDN (to be published on 3/2)
  * [x] NPM (published on 3/1)
    * https://www.npmjs.com/package/botframework-webchat/v/4.12.0
  * [x] Daily build (for RC)
    * https://github.com/microsoft/BotFramework-WebChat/releases/daily

## GitHub Updates
**Create New Branch** @cleemullins
- [x] C# 
- [x] JS 
- [x] Python 
- [x] Java  
- [x] BF-Cli 
- [x] V3 C# & JS - No changes to v3 are needed. 3.30 is already released.

**Setup Branch Protection on New Branch** @cleemullins
- [x] C# (Done)
- [x] JS
- [x] Python
- [x] Java 
- [x] BF-Cli

**Bump Version on Main** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] BF-Cli

**Update Readme.md in main to reflect new branch** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli (No updates to make)

**Branch Samples** @cleemullins
- [ ] C#
- [ ] JS
- [ ] Python

**Create DRAFT Release** @cleemullins
- [x] C# [4.12 DRAFT Release]() 
- [x] JS [4.12 DRAFT Release]() 
- [x] Python [4.12 DRAFT Release](https://github.com/microsoft/botbuilder-python/releases/tag/untagged-d509912f6c3fae35f951) 
- [x] Java [4.6.0-preview8](https://github.com/microsoft/botbuilder-java/releases/tag/untagged-43e003ad4c18f6d27897)
- [x] bf-cli 
- [x] BotFramework-SDK  

**Consolidate release notes and change logs** @cleemullins, @EricDahlvang
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

**Apply Release Notes to DRAFT Release** @cleemullins, @EricDahlvang
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

**Publish GitHub Release** @EricDahlvang
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

**Web Chat** @compulim
- [x] https://github.com/microsoft/BotFramework-WebChat/issues/3731
  - [Release testing page](https://corinagum.github.io/WebChat-release-testing)
  - [Daily build](https://github.com/microsoft/BotFramework-WebChat/releases/daily)
    - [x] Published to NPM: https://www.npmjs.com/package/botframework-webchat/v/4.12.0
    - [ ] Published to CDN
      - https://cdn.botframework.com/botframework-webchat/4.12.0/webchat.js
      - https://cdn.botframework.com/botframework-webchat/4.12.0/webchat-es5.js
      - https://cdn.botframework.com/botframework-webchat/4.12.0/webchat-minimal.js

## Dialtone Echo Skills Tests (Gabo, Monica)
- [ ] Functional Test Pipeline

## Confirm Preview Packages (Gabo)
- [ ] C# (Adaptive Testing)
- [ ] C# (Runtime Plugins)
- [ ] C# (Runtime)
- [ ] C# (Microsoft.Bot.Builder.Parsers.LU)
- [ ] C# (Microsoft.Bot.Builder.AI.Orchestrator)
- [ ] C# (Microsoft.Bot.Builder.Dialogs.Debugging)

## Required Signoff

**Teams**  Sid Uppal, Andrew Clear
- [ ] C# (Ramjot Singh)
- [ ] JS (Robin Liao)

**PVA** Pawan Taparia, Salem Bacha, Karthik Narayanan
- [ ] C# 
- [ ] JS 

**Cortana** Vivek Goswami
- [ ] C#
- [ ] JS 
- [ ] Python

**Virtual Assistant** Darren Jefford / Ted Li / 
- [ ] C# 
- [ ] JS
- [ ] bf-cli

**Emulator** Chris Whitten
- [ ] C# (Chris Whitten) 
- [ ] JS (Chris Whitten)
- [ ] Python (TBD)

## Testing Status 
**Acceptance testing:** @jwiley84, @stevkan 

**Orchestrator Package Works**
- [ ] C#
- [ ] JS

**New Azure Blobs package works** @EricDahlvang 
- [ ] C#
- [ ] JS

**Step Into Debugging**
- [ ] C#
- [ ] JS
- [ ] Python

**Console Adapter**
- [ ] C#
- [ ] JS
- [ ] Python

**Simple Dialog Flow**
- [ ] C#
- [ ] JS
- [ ] Python
- [x] Java

**Simple State Management**
- [ ] C#
- [ ] JS
- [ ] Python
- [x] Java

**Welcome Messages**
- [ ] C#
- [ ] JS
- [ ] Python
- [x] Java

**Prompts and Prompt Validations**
- [ ] C#
- [ ] JS
- [ ] Python
- [x] Java

**Standard Cards**
- [ ] C#
- [ ] JS
- [ ] Python
- [x] Java

**Adaptive Cards**
- [ ] C#
- [ ] JS
- [ ] Python

**Card Actions**
- [ ] C#
- [ ] JS
- [ ] Python
- [x] Java

**Regex Checking**
- [ ] C#
- [ ] JS
- [ ] Python

**QnA Maker**
- [ ] C#
- [ ] JS
- [ ] Python

**LUIS**
- [ ] C#
- [ ] JS
- [ ] Python

**Dispatch**
- [ ] C#
- [ ] JS
- [ ] Python

**Attachments**
- [ ] C#
- [ ] JS
- [ ] Python

**Proactive Messages**
- [ ] C#
- [ ] JS
- [ ] Python
- [x] Java

**Middleware**
- [ ] C#
- [ ] JS
- [ ] Python

**Translations**
- [ ] C#
- [ ] JS
- [ ] Python

**Authentication**
- [ ] C#
- [ ] JS
- [ ] Python
- [x] Java

**Waterfalls and Dialog Sets**
- [ ] C#

**State Storage**
- [ ] C#
- [ ] JS
- [ ] Python

**Transcript Logging**
- [ ] C#
- [ ] JS
- [ ] Python

**Facebook-specific Events**
- [ ] C#
- [ ] JS
- [ ] Python

**Application Insights**
- [ ] C#
- [ ] JS
- [ ] Python

**Teams**
- [ ] C#
- [ ] JS
- [ ] Python
- [x] Java

**Enterprise Bot Template**
- [ ] C#
- [ ] JS
- [ ] Python

**BF-CLI**
- [ ] Global & config
- [ ] Chatdown
- [ ] Luis
- [ ] QnAMaker
