### ISSUE TITLE
R13 Release Checklist

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#6245]
## Package Location
* C# 
** [https://www.nuget.org/packages/Microsoft.Bot.Builder/4.13.0](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.13.0)
* JS (Uses the @rc tag on public NPM)
** [https://www.npmjs.com/package/botbuilder](https://www.npmjs.com/package/botbuilder)
* Python
** https://test.pypi.org/project/botbuilder-core/4.13.0/
* BF CLI (Uses the @rc tag on public NPM)
** https://www.npmjs.com/package/@microsoft/botframework-cli
** https://www.npmjs.com/package/@microsoft/botframework-cli/v/4.13.0
* JAVA
** https://oss.sonatype.org/#nexus-search;quick~com.microsoft.bot
* Web Chat
  * [x] CDN 
  * [x] NPM
  * [x] Daily build (for RC)
    * https://github.com/microsoft/BotFramework-WebChat/releases/daily

## GitHub Updates
**Create New Branch** @cleemullins
- [x] C# 
- [x] JS 
- [x] Python 
- [x] Java  
- [x] BF-Cli 
- [x] Orchestrator
- [x] V3 C# & JS - No changes to v3 are needed. 3.30 is already released.

**Setup Branch Protection on New Branch** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] Orchestrator
- [x] BF-Cli

**Bump Version on Main** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] Orchestrator
- [x] BF-Cli

**Update Readme.md in main to reflect new branch** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [ ] Orchestrator
- [x] bf-cli (No updates to make)

**Branch Samples** @cleemullins
- [x] C#, JS, Python
- [x] Java

**Create DRAFT Release** @EricDahlvang
- [x] C# [4.13 DRAFT Release]() 
- [x] JS [4.13 DRAFT Release]() 
- [x] Python [4.13 DRAFT Release]() 
- [x] Java [4.6.0]()
- [x] bf-cli 
- [x] BotFramework-SDK  

**Consolidate release notes and change logs** @cleemullins, @EricDahlvang
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

**Apply Release Notes to DRAFT Release** @cleemullins, @EricDahlvang
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

**Publish GitHub Release** @EricDahlvang
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

**Web Chat** @compulim
- [x] https://github.com/microsoft/BotFramework-WebChat/issues/3826
  - [Release testing page](https://corinagum.github.io/WebChat-release-testing)
  - [Daily build](https://github.com/microsoft/BotFramework-WebChat/releases/daily)
    - [x] Published to NPM: https://www.npmjs.com/package/botframework-webchat/v/4.13.0
    - [x] Published to CDN: https://cdn.botframework.com/botframework-webchat/4.13.0/webchat.js

## Dialtone Skills Tests (Gabo, Monica)
- [x] Functional Test Pipeline

## Confirm Preview Packages (Monica)
- [x] C# (Adaptive Testing)
- [x] C# (Microsoft.Bot.Builder.Parsers.LU)
- [x] C# (Microsoft.Bot.Builder.Dialogs.Debugging)
- [x] C# (Microsoft.Bot.Builder.Azure.Queues)

## Required Signoff

**Teams**  Sid Uppal, Andrew Clear
- [ ] C#
- [ ] JS

**PVA** Pawan Taparia, Salem Bacha, Karthik Narayanan
- [x] C# 

**Cortana** Vivek Goswami (Inactive)
- [ ] C#
- [ ] JS 
- [ ] Python

**Prebuilt Experiences** Lauren/Thomas
- [ ] C# 
- [ ] JS
- [ ] bf-cli

**Emulator** Chris Whitten
- [x] C# (Chris Whitten) 
- [x] JS (Chris Whitten)
- [x] Python (TBD)

## Testing Status 
**Acceptance testing:** @jwiley84, @stevkan 

- [ ] C# ActivityHandler samples
- [ ] C# CloudAdapter 
- [ ] Javascript
- [ ] Python

**Orchestrator Package Works**
- [ ] C#
- [ ] JS

**New Azure Blobs package works** @EricDahlvang 
- [ ] C#
- [ ] JS

**Step Into Debugging**
- [ ] C#
- [ ] JS
- [ ] Python

**Console Adapter**
- [x] C#
- [x] JS
- [x] Python

**Simple Dialog Flow**
- [x] C#
- [x] JS
- [x] Python
- [x] Java

**Simple State Management**
- [x] C#
- [x] JS
- [x] Python
- [x] Java

**Welcome Messages**
- [x] C#
- [x] JS
- [x] Python
- [x] Java

**Prompts and Prompt Validations**
- [x] C#
- [x] JS
- [x] Python
- [x] Java

**Standard Cards**
- [x] C#
- [x] JS
- [x] Python
- [x] Java

**Adaptive Cards**
- [x] C#
- [x] JS
- [x] Python
- [x] Java

**Card Actions**
- [x] C#
- [x] JS
- [x] Python
- [x] Java

**Regex Checking**
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**QnA Maker**
- [x] C#
- [x] JS
- [x] Java
- [x] Python

**LUIS**
- [x] C#
- [x] JS
- [x] Java
- [x] Python

**Attachments**
- [x] C#
- [x] JS
- [x] Java
- [x] Python

**Proactive Messages**
- [x] C#
- [x] JS
- [x] Python
- [x] Java

**Middleware**
- [x] C#
- [x] JS
- [x] Java
- [x] Python

**Translations**
- [x] C#
- [x] JS
- [x] Java
- [x] Python

**Authentication**
- [x] C#
- [x] JS
- [x] Python
- [x] Java

**Waterfalls and Dialog Sets**
- [x] C#
- [x] JS
- [x] Python
- [x] Java

**State Storage**
- [x] C#
- [x] JS
- [x] Java
- [x] Python

**Transcript Logging**
- [x] C#
- [x] JS
- [x] Java (?)
- [x] Python

**Facebook-specific Events**
- [x] C#
- [x] JS
- [x] Java
- [x] Python

**Application Insights**
- [x] C#
- [x] JS
- [x] Java
- [x] Python

**Teams**
- [x] C#
- [x] JS
- [x] Python
- [x] Java

**Bot Templates**
- [ ] C#
- [ ] JS

**BF-CLI**
- [ ] Global & config
- [ ] Chatdown
- [ ] Luis
- [ ] QnAMaker

** Directline Speech **
- [ ] C#
- [ ] JS
- [ ] Python

** Deploy to Azure using BF CLI **
- [ ] C#
- [ ] JS
- [ ] Python
- [x] Java
