### ISSUE TITLE
R14 Release Checklist

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botframework-sdk#6334]
## Package Location
* C# 
** []()
* JS (Uses the @rc tag on public NPM)
** []()
* Python
**
* BF CLI (Uses the @rc tag on public NPM)
** 
** 
* JAVA
  * [4.14.0-SNAPSHOT](https://oss.sonatype.org/#nexus-search;gav~com.microsoft.bot~~4.14.0-SNAPSHOT~~)
* Web Chat
  * [ ] CDN 
  * [x] NPM (https://www.npmjs.com/package/botframework-webchat/v/4.14.0)
  * [x] Daily build (for RC)

## GitHub Updates
**Create New Branch** @cleemullins
- [x] C# 
- [x] JS 
- [x] Python 
- [x] Java  
- [x] BF-Cli 
- [ ] Orchestrator
- [ ] V3 C# & JS - No changes to v3 are needed. 3.30 is already released.

**Setup Branch Protection on New Branch** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [ ] Orchestrator
- [x] BF-Cli

**Bump Version on Main** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [ ] Orchestrator
- [x] BF-Cli

**Update Readme.md in main to reflect new branch** @cleemullins
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [ ] Orchestrator
- [x] bf-cli (No updates to make)

**Branch Samples** @cleemullins
- [x] C#, JS, Python, Java  [R14Samples](https://github.com/microsoft/BotBuilder-Samples/tree/R14Samples)

**Create DRAFT Release** @EricDahlvang
- [x] C# [4.14 DRAFT Release](https://github.com/microsoft/botbuilder-dotnet/releases) 
- [x] JS [4.14 DRAFT Release](https://github.com/microsoft/botbuilder-js/releases) 
- [x] Python  [4.14.0 DRAFT Release](https://github.com/microsoft/botbuilder-python/releases)
- [x] Java [4.14.0 DRAFT Release](https://github.com/microsoft/botbuilder-java/releases)
- [x] bf-cli [4.14.0 DRAFT Release](https://github.com/microsoft/botframework-cli/releases)
- [x] BotFramework-SDK [4.14.0 DRAFT Release](https://github.com/microsoft/botframework-sdk/releases)
- [x] BotFramework-Components [4.14.0 DRAFT Release](https://github.com/microsoft/botframework-components)

**Consolidate release notes and change logs** @cleemullins, @EricDahlvang
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

**Apply Release Notes to DRAFT Release** @cleemullins, @EricDahlvang
- [x] C#
- [x] JS
- [x] Python
- [x] Java 
- [x] bf-cli

**Publish GitHub Release** @EricDahlvang
- [x] C#
- [x] JS
- [ ] Python
- [ ] Java 
- [x] bf-cli

**Web Chat** @compulim
- [ ] 4.14.0
  - [Release testing page](https://corinagum.github.io/WebChat-release-testing)
  - [Daily build](https://github.com/microsoft/BotFramework-WebChat/releases/daily)
    - [x] Published to NPM: https://www.npmjs.com/package/botframework-webchat/v/4.14.0
    - [ ] Published to CDN: 

## Dialtone Skills Tests (Gabo, Monica)
- [x] Functional Test Pipeline

## Confirm Preview Packages (Monica)
- [x] C# (Adaptive Testing)
- [x] C# (Microsoft.Bot.Builder.Parsers.LU)
- [x] C# (Microsoft.Bot.Builder.Dialogs.Debugging)
- [x] C# (Microsoft.Bot.Builder.Azure.Queues)

## Required Signoff

**Teams**  Sid Uppal, Andrew Clear
- [x] C#
- [ ] JS

**PVA** Pawan Taparia, Salem Bacha, Karthik Narayanan
- [x] C# 

**Cortana** Vivek Goswami (Inactive)
- [ ] C#
- [ ] JS 
- [ ] Python

**Prebuilt Experiences** Lauren/Thomas
- [ ] C# 
- [ ] JS
- [ ] bf-cli

**Emulator** Chris Whitten
- [ ] C# (Chris Whitten) 
- [ ] JS (Chris Whitten)
- [ ] Python (TBD)

## Testing Status 
**Acceptance testing:** @jwiley84, @stevkan 

- [ ] C# ActivityHandler samples
- [ ] C# CloudAdapter 
- [ ] Javascript
- [ ] Python

**Orchestrator Package Works**
- [ ] C#
- [ ] JS

**New Azure Blobs package works** @EricDahlvang 
- [ ] C#
- [ ] JS

**Step Into Debugging**
- [ ] C#
- [ ] JS
- [ ] Python

**Console Adapter**
- [x] C#
- [x] JS
- [x] Python

**Simple Dialog Flow**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Simple State Management**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Welcome Messages**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Prompts and Prompt Validations**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Standard Cards**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Adaptive Cards**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Card Actions**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Regex Checking**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**QnA Maker**
- [x] C#
- [x] JS
- [ ] Java
- [x] Python

**LUIS**
- [x] C#
- [x] JS
- [ ] Java
- [x] Python

**Attachments**
- [x] C#
- [x] JS
- [ ] Java
- [x] Python

**Proactive Messages**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Middleware**
- [x] C#
- [x] JS
- [ ] Java
- [x] Python

**Translations**
- [x] C#
- [x] JS
- [ ] Java
- [x] Python

**Authentication**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Waterfalls and Dialog Sets**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**State Storage**
- [x] C#
- [x] JS
- [ ] Java
- [x] Python

**Transcript Logging**
- [x] C#
- [x] JS
- [ ] Java (?)
- [x] Python

**Facebook-specific Events**
- [x] C#
- [x] JS
- [ ] Java
- [x] Python

**Application Insights**
- [x] C#
- [x] JS
- [ ] Java
- [x] Python

**Teams**
- [x] C#
- [x] JS
- [x] Python
- [ ] Java

**Bot Templates**
- [ ] C#
- [ ] JS

**BF-CLI**
- [ ] Global & config
- [ ] Chatdown
- [ ] Luis
- [ ] QnAMaker

** Directline Speech **
- [ ] C#
- [ ] JS
- [ ] Python

** Deploy to Azure using BF CLI **
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java
